services:
  converter-frontend:
    container_name: "converter-frontend"
    image: ghcr.io/doppeltilde/gelesen-open-source:converter-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL
    restart: unless-stopped