name: Deploy Blog

on:
  push:
    tags:
      - "blog-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    defaults:
      run:
        working-directory: blog
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.21.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy blog/build/jaspr --project-name=gelesen-blog ${{ startsWith(github.ref, 'refs/tags/blog-production-') && ' --branch=production' || '' }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}