name: Deploy WWW

on:
  push:
    tags:
      - "www-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    defaults:
      run:
        working-directory: www
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Activate Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: Build Jaspr app
        run: jaspr build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy www/build/jaspr --project-name=gelesen-open-source
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}