name: Deploy WWW

on:
  push:
    tags:
      - "www-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    defaults:
      run:
        working-directory: www
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.21.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy www/build/jaspr --project-name=gelesen-site --branch=production
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}