name: Deploy Converter

on:
  push:
    tags:
      - "converter-frontend-*"

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-converter-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: "ghcr.io"
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_SECRET: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - docker_file: converter/frontend/Dockerfile
            label: "converter-frontend"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
          labels: |
            type=raw,value=image-type=${{ matrix.label }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./converter/frontend
          file: converter/frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:converter-frontend
          platforms: linux/amd64,linux/arm64